wheel_odom:
  ros__parameters:
    wheelbase: 1.55
    wheel_radius: 0.03
    steer_joint: front_steer_joint
    drive_joints: [rear_left_wheel_joint, rear_right_wheel_joint]

    # 부호/보정
    drive_joint_signs: [1.0, 1.0]   # 전진 시 v가 +가 되도록 필요시 [-1.0, -1.0] 등으로 조정
    steer_sign: 1.0                 # 좌회전이 +yaw(반시계)면 1.0, 반대로 나오면 -1.0
    body_forward_sign: 1.0          # 전진이 +X가 되도록. 필요시 -1.0

    # 프레임/토픽
    odom_frame: odom
    base_frame: base_link
    odom_topic: /wheel_odom
    publish_tf: false

    # IMU 헤딩 사용 권장
    use_imu_heading: true
    imu_topic: /imu/data

    # 스티어 보정
    steer_gain: 1.0
    steer_offset: 0.0
